version: '3.8'
services:
  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=mysqldb
      - MYSQL_USER= user
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - '9411:9411'

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: always

volumes:
  db:
    driver: local
  redis-data:
    driver: local